set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

source-file ~/dotfiles/config/tmux/.tmux.keys.conf
source-file ~/dotfiles/config/tmux/.tmux.utils.conf
if-shell "uname | grep -q Darwin" "source-file ~/dotfiles/config/tmux/.tmux.mac.conf" # mac only
source-file ~/dotfiles/config/tmux/.tmux.theme.conf
