# colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# keys
source-file ~/dotfiles/config/tmux/.tmux.keys.conf

# utils
source-file ~/dotfiles/config/tmux/.tmux.utils.conf

# mac specifics
if-shell "uname | grep -q Darwin" "source-file ~/dotfiles/config/tmux/.tmux.mac.conf"

# theme
source-file ~/dotfiles/config/tmux/.tmux.theme.conf
