source "$HOME/dotfiles/config/zsh/theme.zsh"
source "$HOME/dotfiles/config/zsh/keys.zsh"
source "$HOME/dotfiles/config/zsh/history.zsh"
source "$HOME/dotfiles/config/zsh/functions.zsh"
source "$HOME/dotfiles/config/zsh/aliases.zsh"
source "$HOME/dotfiles/config/zsh/mac.zsh"
source "$HOME/dotfiles/config/zsh/auto.zsh"
