gui:
  authorColors:
    "*": "#f3be7c"
  theme:
    activeBorderColor:
      - "#cdcdcd" # - "#aeaed1"
      - "bold"
    inactiveBorderColor:
      - "#878787" # - "#606079"
    optionsTextColor:
      - "#c48282" # - "#606079"
    selectedLineBgColor:
      - "#333738" # - "#252530"
    cherryPickedCommitFgColor:
      - "#c48282" # - "#d8647e"
    cherryPickedCommitBgColor:
      - "#aeaed1" # - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"
    searchingActiveBorderColor:
      - "#cdcdcd"
      - "bold"
#gui:

  # line by line staging
  useHunkModeInStagingView: false

git:
  # dont ask for gpg password
  overrideGpg: true
  # use delta as pager
  diffRenderers:
    - command: delta --dark --paging=never --tabs 4
  # disable force pushing
  disableForcePushing: true

os:
  # nvim as editor
  editPreset: 'nvim'

customCommands:
  - key: '<alt-p>'
    command: 'git pull --rebase'
    context: 'global'
    description: 'Pull with rebase'
