gui:
  authorColors:
    "*": "#f3be7c"
  theme:
    activeBorderColor:
      - "#cdcdcd" # - "#aeaed1"
      - "bold"
    inactiveBorderColor:
      - "#878787" # - "#606079"
    optionsTextColor:
      - "#c48282" # - "#606079"
    selectedLineBgColor:
      - "#333738" # - "#252530"
    cherryPickedCommitFgColor:
      - "#c48282" # - "#d8647e"
    cherryPickedCommitBgColor:
      - "#aeaed1" # - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"

    searchingActiveBorderColor:
      - "#cdcdcd"
      - "bold"

git:
  paging:
    pager: delta --dark --paging=never

  disableForcePushing: true

os:
  editPreset: 'nvim'