setw -g mode-keys vi
set -g mouse on

# ctrl s prefix
set -g prefix C-s

# resize
bind j resize-pane -D 5
bind k resize-pane -U 5
bind h resize-pane -L 5
bind l resize-pane -R 5

# / and \ for splitting (C- for current dir)
unbind %
unbind '"'
bind \\ split-window -h -c ~/
bind / split-window -v -c ~/
bind C-\\ split-window -h -c '#{pane_current_path}'
bind C-_ split-window -c '#{pane_current_path}' # ^_ is ^/

# new window in current path or ~
bind c new-window -c ~/
bind C-c new-window -c '#{pane_current_path}'

# quit current
bind q kill-window

# auto rename current
bind C-, rename-window "#{b:pane_current_path}"

# r to reload config
unbind r
bind r source-file ~/.tmux.conf
