# colors
set -g @thm_alt "#252530"
set -g @thm_blue "#6e94b2"
set -g @thm_purple "#aeaed1"
set -g @thm_pink "#bb9dbd"
set -g @thm_red "#c48282"
set -g @thm_black "#141415"
set -g @thm_white "#cdcdcd"

# Configure Tmux
set -g status-position bottom
set -g status-style "bg=default"
set -g status-justify absolute-centre
set -g status-bg default

# pane border look and feel
setw -g pane-border-status off
setw -g pane-border-style fg=#cdcdcd
setw -g pane-active-border-style fg=#6e94b2

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_alt},fg=default,bold]  #S },#{#[bg=default,fg=#{@thm_blue}]  #S }}"
set -ga status-left "#[bg=default,fg=#{@thm_alt},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_purple}]  #{pane_current_command} "
set -ga status-left "#[bg=default,fg=#{@thm_alt},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_pink}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=default,fg=#{@thm_purple}]#(whoami) "

# window look and feel
set -g automatic-rename-format ""
set -g renumber-windows on

set -g window-status-format " #{?#{!=:#{window_name},},#I: #W,#I} "
set -g window-status-style "bg=default,fg=#{@thm_white}"
set -g window-status-last-style "bg=default,fg=#{@thm_red}"
set -g window-status-activity-style "bg=#{@thm_purple},fg=default"
set -g window-status-bell-style "bg=#{@thm_purple},fg=default,bold"
set -gF window-status-separator "#[bg=default,fg=#{@thm_alt}]│"

set -g window-status-current-format " #{?#{!=:#{window_name},},#W,#I} "
set -g window-status-current-style "bg=#{@thm_red},fg=#{@thm_black},bold"
