
# documents projects picker
bind C-space display-popup -w 50% -h 40% -b none -E \
	"find ~/Documents/ -type d -mindepth 2 -maxdepth 2 -type d -not -path '*/\\.*' \
	| sed 's/^\\/Users\\/twhlynch\\/Documents\\///' \
	| fzf | xargs -I{} tmux new-window -c \"$HOME/Documents/{}\" && tmux send-keys 'nvim .' C-m"

# lazygit popup
bind g run "cd '#{pane_current_path}' && git rev-parse --git-dir >/dev/null 2>&1 \
	&& tmux display-popup -w 90% -h 90% -b none -E 'cd \'#{pane_current_path}\' && lazygit' \
	|| tmux display-message 'Not in a Git repository'"

# fzf then open urls in view # grep -oE couldnt handle '[^\]]'
bind u display-popup -w 50% -h 40% -b none -E \
	"tmux capture-pane -J -p \
	| rg -o '(https?)://[^>\s\"'\\''\\]]*[^>\s.,;:!?)\"'\\''\\]]' \
	| fzf | xargs open"

# same but all history
bind C-u display-popup -w 50% -h 40% -b none -E \
	"tmux capture-pane -J -p -S - \
	| rg -o '(https?)://[^>\s\"'\\''\\]]*[^>\s.,;:!?)\"'\\''\\]]' \
	| fzf | xargs open"

