
# quick open binds (not ELM)
bind D new-window -c ~/dotfiles                              \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind G new-window -c ~/Documents/root/Games/GRAB-Game        \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind W new-window -c ~/Documents/SlinDev/GRAB-Website        \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind R new-window -c ~/Documents/root/Rayne                  \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind T new-window -c ~/Documents/GRAB/GRAB-Tools             \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind A new-window -c ~/Documents/GRAB/GRAB-Tools-API         \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind F new-window -c ~/Documents/Personal/twhlynch.github.io \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind B new-window -c ~/Documents/Personal/blog               \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind H new-window -c ~/Documents/RISC                        \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind V new-window -c ~/Documents/HIVE/GCS                    \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;
bind C new-window -c ~/Documents/root/Games/CubeGame         \; send-keys "nvim ." C-m \; rename-window "#{b:pane_current_path}" \;

